version: "3.8"

services:
  react-app:
    image: react-app
    container_name: react-app
    ports:
      - "3000:3000"
  nginx-server:
    image: nginx-server
    container_name: nginx-server
    ports:
      - "80:80"
